"""Fix comment post relation mismatch

Revision ID: 3bf0ec091b48
Revises: 7f165d2e786a
Create Date: 2026-04-18 15:01:20.409141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf0ec091b48'
down_revision: Union[str, Sequence[str], None] = '7f165d2e786a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
